/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * Instant Connect API
 * The Instant Connect API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  email?: string;
  name?: string;
}
